openapi: '3.0.3'

info:
  title: Recruit API
  description: Recruit API for wanted pre-onboarding course
  version: 1.0.0

basePath: "/"

schemes:
  - http

paths:
  /opening:
    post:
      description: 요구사항 1. 채용공고를 등록합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                company_id:
                  type: number
                  example: 1
                country:
                  type: string
                  example: 대한민국
                location:
                  type: string
                  example: 서울
                position:
                  type: string
                  example: 백엔드 엔지니어
                reward:
                  type: number
                  example: 5000000
                content:
                  type: string
                  example: Wanted is still hungry! Better and Better!!!!
                tech_stack:
                  type: string
                  example: express
              required:
                - company_id
                - country
                - location
                - position
                - content
                - tech_stack
      responses:
        '201':
          description: Created
        '404':
          description: "${company_id} doesn't exist in company table."
    get:
      description: 요구사항 4-1. 사용자는 채용공고 목록을 확인할 수 있습니다(채용내용은 상세 페이지에서 표시).
      parameters: [ ]
      responses:
        '200':
          description: OK
  "/opening?search=wanted":
    get:
      description: 요구사항 4-2. 채용공고 검색 기능 구현(네글자 이상만 지원합니다)
      parameters:
        - in: query
          name: search
          value: wanted
      responses:
        '200':
          description: OK
  "/opening/{id}":
    patch:
      description: 요구사항 2. 채용공고를 수정합니다.
      parameters:
        - name: id
          in: path
          required: true
          type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                country:
                  type: string
                  example: 미국
                location:
                  type: string
                  example: 실리콘밸리
                position:
                  type: string
                  example: 백엔드 엔지니어
                reward:
                  type: number
                  example: 5000000
                content:
                  type: string
                  example: Netflix is still hungry! Better and Better!!!!
                tech_stack:
                  type: string
                  example: express
      responses:
        '200':
          description: OK
        '400':
          description: id value cannot be 'modified'.
        '404':
          description: "${opening_id} doesn't exist in opening table."
    delete:
      description: 요구사항 3. 채용공고를 삭제합니다.
      parameters:
        - name: id
          in: path
          required: true
          type: number
      responses:
        '200':
          description: OK
        '404':
          description: "${opening_id} doesn't exist in opening table."
    get:
      '404':
        description: "${opening_id} doesn't exist in opening table."
      description: 요구사항 5. 채용 상세 페이지를 가져옵니다 (채용내용, 해당 회사가 올린 다른 채용공고가 추가적으로 포함됩니다).
      parameters:
        - name: id
          in: path
          required: true
          type: number
      responses:
        '200':
          description: OK
        '404':
          description: "${opening_id} doesn't exist in opening table."
  /job-application:
    post:
      description: 요구사항 6. 사용자는 채용공고에 지원합니다(1회만 가능).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                opening_id:
                  type: number
                  example: 2
                applicant_id:
                  type: number
                  example: 1
              required:
                - opening_id
                - applicant_id
      responses:
        '201':
          description: Created
        '400':
          description: 해당 채용공고에는 1회만 지원 가능합니다.
        '404':
          description: "${opening_id} doesn't exist in opening table. || ${applicant_id}
            doesn't exist in applicant table."
